apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: backend
    environment: dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-sql-sa
  annotations:
    iam.gke.io/gcp-service-account: <GCP-Service-Account-name>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceaccountName: ksa-sql-sa
      containers:
      - name: frontend
        image: be-appserver:latest
        ports:
        - containerPort: 80
        securityContext:
          runasUser: 1001
          runasGroup: 1001
      - name: cloud-sql-proxy
        image: gce-proxy:1.24.0
        command:
          - "/cloud_sql_proxy"
          - "ip_address_type=PRIVATE"
          - "instances=<INSTANCE_CONNECTION_NAME>=tcp:5432"
        securityContext:
          runasUser: 1001
          runasGroup: 1001
          
